FROM pytorch/pytorch:latest

ARG FRAMEWORK="sanic"

WORKDIR /workspace

COPY src ./src
COPY requirements.txt ./requirements.txt

RUN apt-get update && apt-get install -y libev-dev
RUN pip install -r requirements.txt

# REST
EXPOSE 8501

ENTRYPOINT ["python -m src.${FRAMEWORK}_app"]