FROM pytorch/pytorch:latest

WORKDIR /workspace

COPY src ./src
COPY requirements.txt ./requirements.txt

RUN apt-get update && apt-get install -y libev-dev
RUN pip install -r requirements.txt

# REST
EXPOSE 8501

RUN echo "python -m src.wsgi" > ./run_server.sh && chmod +x ./run_server.sh

ENTRYPOINT ["/bin/bash", "./run_server.sh"]