FROM pytorch/pytorch:latest

WORKDIR /workspace

COPY src ./src
COPY requirements.txt ./requirements.txt

RUN apt-get update && apt-get install -y libev-dev
RUN pip install -r requirements.txt

# REST
EXPOSE 8501

RUN echo -e "/bin/bash\n\n python -m src.wsgi" > ./run_server.sh && chmod +x ./run_server.sh

ENTRYPOINT ["./run_server.sh"]